# Generated by Django 4.1.4 on 2022-12-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
    ]
