# Generated by Django 4.1.4 on 2022-12-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_product_productmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
